### PR TITLE
feat: install go as non-root

### PR DESCRIPTION
**Pull request by rarkins**
Go often chowns cache files as root, which means you need to `sudo` when cleaning up the cache, which is undesirable. This refactor attempts to resolve this by installing go while authenticated as user “ubuntu”.

### CODE REVIEW

**Comment by rarkins** [comment]
@moorara @paultyng do you see any problem with this approach?

**Comment by rarkins** [comment]
By the way, I'm not too sure how the `GOPATH` matters for a Renovate project. Currently it's set to `/go`, which is pretty arbitrary.

**Comment by moorara** [comment]
@rarkins I think it makes sense to run `go` as a non-root user. Can't think of any problem.
Regarding `GOPATH` I think it is still relevant. Not all projects and repos using the new Go modules yet. Go modules are aslo downloaded to `/go/pkg/mod` path.

Not sure, if I answered your questions though :-)

**Comment by rarkins** [comment]
Technically it always runs as ubuntu yet somehow is writing files to cache sometimes as root. Anyway hopefully this fixes it.

**Pull request closed without merging**
